#ifndef __POKEMON_TCG_SDK_URLS__
#define __POKEMON_TCG_SDK_URLS__

#define POKEMON_TCG_SDK_BASE_URL "https://api.pokemontcg.io/v2/"
#define POKEMON_TCG_SDK_CARDS_URL POKEMON_TCG_SDK_BASE_URL "cards/"
#define POKEMON_TCG_SDK_SETS_URL POKEMON_TCG_SDK_BASE_URL "sets/"
#define POKEMON_TCG_SDK_TYPES_URL POKEMON_TCG_SDK_BASE_URL "types/"
#define POKEMON_TCG_SDK_SUBTYPES_URL POKEMON_TCG_SDK_BASE_URL "subtypes/"
#define POKEMON_TCG_SDK_SUPERTYPES_URL POKEMON_TCG_SDK_BASE_URL "supertypes/"
#define POKEMON_TCG_SDK_RARITIES_URL POKEMON_TCG_SDK_BASE_URL "rarities/"


#endif /*__POKEMON_TCG_SDK_URLS__*/